### ISSUE TITLE
Question regarding power supply

### ISSUE THREAD

**Issue by pareshchouhan** [juekr/remote-friendship-lamp#1]
I have a WS2812-16 Ring RGB LED board, are you sure the power supply by nodemcu v3 VV pin is enough to drive all these LED's? 
For me, the LED's doesn't seem to power ON, either the LEDs are broken or the power supply isn't working, or I am doing something wrong. 
confused :(

**Comment by juekr** [comment]
I have build it with these exact components at least four times – and it worked every time.
